[tox]
envlist =
  py{38,39,310,311,py37,py38,py39}-pytest{6,7,8,9}

[testenv]
deps =
    pexpect
    pytest6: pytest>6.0,<7.0
    pytest6: pytest-xdist
    pytest7: pytest>7.0,<8.0
    pytest7: pytest-xdist
    pytest8: pytest>8.0,<9.0
    pytest8: pytest-xdist
    pytest9: pytest>9.0,<10.0
    pytest9: pytest-xdist
commands = pytest {posargs}
